#!/usr/bin/env python3
"""Generate the local RTL8822C table header from the pinned Linux source."""

from __future__ import annotations

import argparse
import pathlib
import re
import sys


SOURCE_COMMIT = "a56bcd26e770257612a0803249cbd4095fc6feca"
ARRAYS = (
    "rtw8822c_mac",
    "rtw8822c_agc",
    "rtw8822c_bb",
    "rtw8822c_rf_a",
    "rtw8822c_rf_b",
    "rtw8822c_dpk_afe_no_dpk",
    "rtw8822c_dpk_afe_is_dpk",
    "rtw8822c_dpk_mac_bb",
    "rtw8822c_array_mp_cal_init",
)


def extract_array(source: str, name: str) -> str:
    pattern = re.compile(
        rf"static const u32 {re.escape(name)}\[\] = \{{(.*?)\n\}};",
        re.DOTALL,
    )
    matches = pattern.findall(source)
    if len(matches) != 1:
        raise ValueError(f"expected exactly one Linux array named {name}")
    return matches[0][1:] if matches[0].startswith("\n") else matches[0]


def generate(source: str) -> str:
    chunks = [
        "/* SPDX-License-Identifier: BSD-3-Clause */\n",
        "/*\n",
        " * Auto-generated by scripts/generate_rtl8822c_tables.py from Linux\n",
        f" * rtw88 rtw8822c_table.c at commit {SOURCE_COMMIT}.\n",
        " * Copyright (c) 2018-2019 Realtek Corporation.\n",
        " * Do not edit generated table data by hand.\n",
        " */\n",
        "#ifndef __RTW8822C_TABLES_H__\n",
        "#define __RTW8822C_TABLES_H__\n\n",
    ]
    for name in ARRAYS:
        chunks.extend(
            (f"static const UInt32 {name}[] = {{\n", extract_array(source, name), "\n};\n\n")
        )
    chunks.append("#endif\n")
    return "".join(chunks)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("linux_table", type=pathlib.Path)
    parser.add_argument("output", type=pathlib.Path)
    args = parser.parse_args()

    try:
        source = args.linux_table.read_text(encoding="utf-8")
        rendered = generate(source)
    except (OSError, UnicodeError, ValueError) as error:
        print(f"table generation failed: {error}", file=sys.stderr)
        return 1

    args.output.parent.mkdir(parents=True, exist_ok=True)
    with args.output.open("w", encoding="utf-8", newline="\n") as output:
        output.write(rendered)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
